language: node_js
node_js:
- '6'
script:
- npm test
before_deploy: echo 'Deploying to npm'
deploy:
  provider: npm
  email: george.aidonidis@gmail.com
  api_key:
    secure: PhNAe7pV3Bsbnh8Ewo1Ku88QrXWx0yJdSa6m4xXv8nrC/kM8My2E8V9ui3u0xtHq9yWm5/1nt7BKwU81MHSkWZ0wYujDhLN6eND+aukyWs2zYIZAlCStLOy/vpNyOavIHpGmbTU8eL0HzzwsTepCuxknF9xxsYvtkMv5DhdDdpxvDwOZQql6Bc/6ZCEAk25EcGz8i7g9lnCX4fDTspu52/lcs3RDdDtWo8QtWPVP8MYh8knEdP2p8OqhMVJAborX2kXVv8lcDs929RYJnHK9G64b8hZ4Pp7KwpneKTC6n6gvUuuZXfn6EyCIund6CVHZ3Db5IX4eXJc/ZqJrPElAUcAFWmxkQEoUkYWLTE2qM6iV6APHccz+lGzioTvQcMWQo/ATdzW+3AWpxca2Wkn+0f+heaSzfA7zDZ6/b/2mCdVNK5UaXJVAKZX458zUnI81MBzrE+MwJgTi7hqkMIB6r7v0nItgOoWh9HZX+vFKGS8rEhCNoD6/1qSKjC9LlQH8V9VcX0LvApGsEBYjj7Y2kAioF6cXdBrpAVV7gv2QzMNTlNWWmLQHge1vZvJUjgVwAPL04nn0qUuHjk2zaEnT4KTNmwk4NHO+i3bk0pxRYZZLnkxXy4xejyd42qCSRrBSwtK2aCxP4goDahBQD+cDi7OhkinVi/NkH7UG7lZmrqg=
  on:
    tags: true
    repo: George-Aidonidis/js-travis-npm
